PROJECT_NAME = contiki_ng

# Especificación del módulo de Contiki-NG
CONTIKI_PROJECT = web_sense_process webserver_process

all: $(CONTIKI_PROJECT)

CONTIKI = /../../..

MODULES += os/net/app-layer/coap
MODULES += os/services/rest-engine
MODULES += os/dev/sht11
MODULES += os/dev/light-sensor

include $(CONTIKI)/Makefile.include
